apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-visoft-dev
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production-cloudflare-visoft-dev
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
