all:
  hosts:
    cluster:
      ansible_host: 10.3.3.128
    node1:
      ansible_host: 10.3.3.128
      access_ip: 10.3.3.128
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
